inputs:
  port:
    description: 'Port for app'
    default: 7001
  environment:
    description: 'Env name for var'
    default: 'Dev'
runs:
  using: "composite"
  steps: 
    - name: Checkout repository
      uses: actions/checkout@v3.5.2
      shell: cmd
      with:
        repository: mtararujs/python-greetings 
        path: python-greetings
        
    - name: Stop existing service (${{inputs.environment}})
      run: pm2 delete greetings-app-${{inputs.environment}} & set "errorlevel=0"
      shell: cmd
      working-directory: python-greetings

    - name: Start service (${{inputs.environment}})
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} -o ${{inputs.port}}
      shell: cmd
      working-directory: python-greetings