name: Delivery Pipeline
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test-something:
    runs-on: self-hosted
    steps:
      - name: test pip
        run: pip --version 
      - name: test pm2
        run: pm2 ping

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: python-greetings

  deploy-to-dev:
    name: Deploy Dev
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: ../.github/actions/deploy
        with:
          port: 7001
          enviroment: 'dev'

  tests-on-dev:
      runs-on: self-hosted
      needs: deploy-to-dev
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3.5.2
          with:
            repository: mtararujs/course-js-api-framework
            path: course-js-api-framework
        - name: Install npm dependencies
          run: npm install
          working-directory: course-js-api-framework
        - name: Run tests (Dev)
          run: npm run greetings greetings_dev
          working-directory: course-js-api-framework
