name: Delivery Pipeline
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test-something:
    runs-on: self-hosted
    steps:
      - name: test pip
        run: pip --version 
      - name: ... buil success ...
        run: echo ... buil success ...

  install-pip-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: python-greetings

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: install-pip-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings 
          path: python-greetings
      - name: Stop existing service (Dev)
        run: pm2 delete greetings-app-dev || true
        working-directory: python-greetings
      - name: Start service (Dev)
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
        working-directory: python-greetings

  tests-on-dev:
      runs-on: ubuntu-latest
      needs: deploy-to-dev
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3.5.2
          with:
            repository: mtararujs/course-js-api-framework
            path: course-js-api-framework
        - name: Install npm dependencies
          run: npm install
          working-directory: course-js-api-framework
        - name: Run tests (Dev)
          run: npm run greetings greetings_dev
          working-directory: course-js-api-framework
