name: Delivery Pipeline
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.2
        
      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
          ref: 4e911440a9886c7c26ccbb4eb55f0bc2a5067b51
          fetch-depth: 0

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        shell: cmd
        working-directory: python-greetings

  deploy-to-dev:
    name: Deploy Dev
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: ./../hello-world/.github/actions/deploy
        with:
          port: 7001
          enviroment: 'dev'

  tests-on-dev:
      runs-on: self-hosted
      needs: deploy-to-dev
      steps:
        - uses: ./../hello-world/.github/actions/tests
          with:
            enviroment: 'dev'
  
  deploy-to-stg:
    name: Deploy Dev
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: ./../hello-world/.github/actions/deploy
        with:
          port: 7002
          enviroment: 'stg'

  tests-on-stg:
      runs-on: self-hosted
      needs: deploy-to-stg
      steps:
        - uses: ./../hello-world/.github/actions/tests
          with:
            enviroment: 'stg'

  deploy-to-preprod:
    name: Deploy Dev
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - uses: ./../hello-world/.github/actions/deploy
        with:
          port: 7003
          enviroment: 'preprod'

  tests-on-preprod:
      runs-on: self-hosted
      needs: deploy-to-preprod
      steps:
        - uses: ./../hello-world/.github/actions/tests
          with:
            enviroment: 'preprod'

  deploy-to-prod:
    name: Deploy Dev
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: ./../hello-world/.github/actions/deploy
        with:
          port: 7004
          enviroment: 'prod'

  tests-on-prod:
      runs-on: self-hosted
      needs: deploy-to-prod
      steps:
        - uses: ./../hello-world/.github/actions/tests
          with:
            enviroment: 'prod'